name: Setup Rust
description: Rust toolchain, cargo cache and public workspace build dependencies.

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libcap-dev clang pkg-config

    - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
      with:
        toolchain: 1.94.1
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
