[workspace]
release = false
publish = false
changelog_update = false
git_release_enable = true
git_release_type = "auto"

[[package]]
name = "flamingo-verifier-client"
release = true
publish = true
changelog_update = true
changelog_path = "CHANGELOG.md"
