[package]
name = "flamingo-verifier-worker-rpc"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
flamingo-verifier-worker-protocol.workspace = true
metrics.workspace = true
thiserror.workspace = true
tracing.workspace = true
