[package]
name = "flamingo-verifier-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "verifier-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ark-babyjubjub.workspace = true
flamingo-verifier-enclave-types.workspace = true
flamingo-verifier-protocol.workspace = true
flamingo-verifier-sealed-types.workspace = true
eddsa-babyjubjub.workspace = true
face-engine.workspace = true
hex.workspace = true
image.workspace = true
pontifex = { workspace = true, features = ["nsm", "server", "channel"] }
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
