[package]
name = "flamingo-verifier-protocol"
description = "Match-token protocol for the Flamingo verifier"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = true
[dependencies]
ark-babyjubjub.workspace = true
ark-ff.workspace = true
coset.workspace = true
eddsa-babyjubjub.workspace = true
poseidon2.workspace = true
serde.workspace = true
serde_bytes.workspace = true

[dev-dependencies]
rand.workspace = true
