[package]
name = "flamingo-verifier-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
flamingo-verifier-sealed-types.workspace = true
hex.workspace = true
sha2.workspace = true
tokio.workspace = true
flamingo-verifier-client.workspace = true
